### ISSUE TITLE
Add 'Sofia' (city) in Bulgaria (country)

### ISSUE THREAD

**Issue by nblkmal** [Chamara-g/rc-geographic#1]
One of our users reported that Sofia, the capital city of Bulgaria, is missing and should be under Bulgaria

<img width="401" alt="Screenshot 2023-09-20 at 9 16 43 AM" src="https://github.com/Chamara-g/rc-geographic/assets/72432370/99b535d3-a5e2-4a42-af68-b5dc938c7531">

**Comment by Chamara-g** [comment]
Fixed this issue in #2
